replicaCount: 1

image:
  repository: vladimirkhil/appregistryservice
  pullPolicy: IfNotPresent
  tag: 1.0.10

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: false
  className: nginx
  clientSecret: ''
  hosts: []
  tls: []

resources: {}

database:
  host: ''
  name: 'appregistry'
  user: 'postgres'
  passwordKey: ''
  passwordValue: 'postgres-password'
  backup:
    enabled: false
    schedule: '0 0 * * *' # Run every day at midnight
    imageVersion: 15
    securityContext: {}
    volumePath: ''

options:
  logLevel: Warning
  otel:
    uri: 'http://localhost:4317'
    metric:
      exportInterval: 60000