apiVersion: v1
entries:
  appregistry:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2024-02-22T21:50:15.8396424+01:00"
    description: A service for storing app releases, installers, runs and errors info
    digest: 69cfc88273370554e69e6e776ab1036a358b21de4cc050d3f0b666864bdad852
    name: appregistry
    type: application
    urls:
    - appregistry-1.0.0.tgz
    version: 1.0.0
generated: "2024-02-22T21:50:15.8366264+01:00"
