apiVersion: v1
entries:
  appregistry:
  - apiVersion: v2
    appVersion: 1.1.1
    created: "2024-12-05T08:29:47.6750444+01:00"
    description: A service for storing app releases, installers, runs and errors info
    digest: 6f1495d001eebbb5de90755bbef2fa199af4ea0413ecfff642fbda6c7e0da6c4
    name: appregistry
    type: application
    urls:
    - appregistry-1.1.1.tgz
    version: 1.1.1
  - apiVersion: v2
    appVersion: 1.1.0
    created: "2024-12-05T08:29:47.6745022+01:00"
    description: A service for storing app releases, installers, runs and errors info
    digest: 31df899d3406de61cf34fc28d1eee57ee5a0daf2f1472a632407983935fc3ef5
    name: appregistry
    type: application
    urls:
    - appregistry-1.1.0.tgz
    version: 1.1.0
  - apiVersion: v2
    appVersion: 1.0.2
    created: "2024-12-05T08:29:47.6621712+01:00"
    description: A service for storing app releases, installers, runs and errors info
    digest: 2046dd36ff4d13e1436f44dde3659db164e95e3c5cf17bc0d7d36fc2c4030d5d
    name: appregistry
    type: application
    urls:
    - appregistry-1.0.2.tgz
    version: 1.0.2
  - apiVersion: v2
    appVersion: 1.0.1
    created: "2024-12-05T08:29:47.6489014+01:00"
    description: A service for storing app releases, installers, runs and errors info
    digest: ad6994cc5f82dcd6c4a8971d60463c533247ee3d846094b9eeaadd8ffc4e015b
    name: appregistry
    type: application
    urls:
    - appregistry-1.0.1.tgz
    version: 1.0.1
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2024-12-05T08:29:47.637173+01:00"
    description: A service for storing app releases, installers, runs and errors info
    digest: 69cfc88273370554e69e6e776ab1036a358b21de4cc050d3f0b666864bdad852
    name: appregistry
    type: application
    urls:
    - appregistry-1.0.0.tgz
    version: 1.0.0
generated: "2024-12-05T08:29:47.6240152+01:00"
